; ===========================================================================
;  PlatformIO Project Configuration for ESP32-S3 SD Web File Server / SD HUB
; ===========================================================================

[platformio]
src_dir = .

[env:esp32s3_sd_hub]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino

; 16MB Flash + 8MB Octal PSRAM + 240MHz CPU Hardware Mapping
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_src_filter = +<ESP32S3_SD_Web_File_Server.ino> +<*.h>

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_IDF_TARGET_ESP32S3
    -DIP_NAPT=1
    -DIP_PORTMAP=1

monitor_speed = 115200
upload_speed = 921600
